# Generated by Django 4.1 on 2022-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('Seafood', 'Seafood'), ('Dairy', 'Dairy'), ('other', 'other'), ('Garnishes', 'Garnishes'), ('Herbs and Spices', 'Herbs and Spices'), ('Nuts and seeds', 'Nuts and seeds'), ('Fruits', 'Fruits'), ('Vegetable', 'Vegetable'), ('Legumes', 'Legumes'), ('Grains', 'Grains'), ('Baked Goods', 'Baked Goods')], default='other', max_length=50),
        ),
    ]
