# Generated by Django 4.1 on 2022-08-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0002_alter_measured_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('Garnishes', 'Garnishes'), ('Seafood', 'Seafood'), ('Baked Goods', 'Baked Goods'), ('Nuts and seeds', 'Nuts and seeds'), ('Fruits', 'Fruits'), ('Herbs and Spices', 'Herbs and Spices'), ('Legumes', 'Legumes'), ('Vegetable', 'Vegetable'), ('other', 'other'), ('Dairy', 'Dairy'), ('Grains', 'Grains')], default='other', max_length=50),
        ),
    ]
