# Generated by Django 4.1 on 2022-08-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0005_alter_measured_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('Legumes', 'Legumes'), ('other', 'other'), ('Herbs and Spices', 'Herbs and Spices'), ('Dairy', 'Dairy'), ('Grains', 'Grains'), ('Fruits', 'Fruits'), ('Garnishes', 'Garnishes'), ('Seafood', 'Seafood'), ('Baked Goods', 'Baked Goods'), ('Nuts and seeds', 'Nuts and seeds'), ('Vegetable', 'Vegetable')], default='other', max_length=50),
        ),
    ]
