# Generated by Django 4.1 on 2022-08-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0006_alter_measured_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('other', 'other'), ('Nuts and seeds', 'Nuts and seeds'), ('Vegetable', 'Vegetable'), ('Baked Goods', 'Baked Goods'), ('Dairy', 'Dairy'), ('Legumes', 'Legumes'), ('Grains', 'Grains'), ('Herbs and Spices', 'Herbs and Spices'), ('Seafood', 'Seafood'), ('Garnishes', 'Garnishes')], default='other', max_length=50),
        ),
    ]
