# Generated by Django 4.1 on 2022-08-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0007_alter_measured_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('Nuts and seeds', 'Nuts and seeds'), ('Legumes', 'Legumes'), ('other', 'other'), ('Seafood', 'Seafood'), ('Grains', 'Grains'), ('Vegetable', 'Vegetable'), ('Garnishes', 'Garnishes'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Herbs and Spices', 'Herbs and Spices'), ('Baked Goods', 'Baked Goods')], default='other', max_length=50),
        ),
    ]
