# Generated by Django 4.1 on 2022-08-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0009_alter_measured_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('Grains', 'Grains'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('other', 'other'), ('Legumes', 'Legumes'), ('Garnishes', 'Garnishes'), ('Nuts and seeds', 'Nuts and seeds'), ('Seafood', 'Seafood'), ('Baked Goods', 'Baked Goods'), ('Vegetable', 'Vegetable'), ('Herbs and Spices', 'Herbs and Spices')], default='other', max_length=50),
        ),
    ]
