# Generated by Django 4.1 on 2022-08-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0011_alter_measured_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('Dairy', 'Dairy'), ('Grains', 'Grains'), ('Herbs and Spices', 'Herbs and Spices'), ('Seafood', 'Seafood'), ('Garnishes', 'Garnishes'), ('Vegetable', 'Vegetable'), ('Baked Goods', 'Baked Goods'), ('Fruits', 'Fruits'), ('other', 'other'), ('Legumes', 'Legumes'), ('Nuts and seeds', 'Nuts and seeds')], default='other', max_length=50),
        ),
    ]
