# Generated by Django 4.1 on 2022-08-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0012_alter_measured_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('other', 'other'), ('Dairy', 'Dairy'), ('Grains', 'Grains'), ('Fruits', 'Fruits'), ('Vegetable', 'Vegetable'), ('Garnishes', 'Garnishes'), ('Legumes', 'Legumes'), ('Seafood', 'Seafood'), ('Nuts and seeds', 'Nuts and seeds'), ('Herbs and Spices', 'Herbs and Spices'), ('Baked Goods', 'Baked Goods')], default='other', max_length=50),
        ),
    ]
