# Generated by Django 4.1 on 2022-08-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0014_alter_measured_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('Seafood', 'Seafood'), ('Dairy', 'Dairy'), ('Vegetable', 'Vegetable'), ('Garnishes', 'Garnishes'), ('Fruits', 'Fruits'), ('Herbs and Spices', 'Herbs and Spices'), ('Grains', 'Grains'), ('Baked Goods', 'Baked Goods'), ('Nuts and seeds', 'Nuts and seeds'), ('Legumes', 'Legumes'), ('other', 'other')], default='other', max_length=50),
        ),
    ]
