# Generated by Django 4.1 on 2022-08-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiz', '0015_alter_measured_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measured_ingredients',
            name='category',
            field=models.CharField(choices=[('Baked Goods', 'Baked Goods'), ('other', 'other'), ('Legumes', 'Legumes'), ('Vegetable', 'Vegetable'), ('Fruits', 'Fruits'), ('Nuts and seeds', 'Nuts and seeds'), ('Garnishes', 'Garnishes'), ('Dairy', 'Dairy'), ('Seafood', 'Seafood'), ('Grains', 'Grains'), ('Herbs and Spices', 'Herbs and Spices')], default='other', max_length=50),
        ),
    ]
